/*
 *  Copyright 2018 People Power Company
 *
 *  This code was developed with funding from People Power Company
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
*/
#include <stdio.h>
#include <errno.h>
#include <memory.h>

#include "pu_logger.h"
#include "pc_config.h"
#include "lib_http.h"
#include "cJSON.h"

#include "OOBE_defaults.h"
#include "oobe_config.h"

/*
 Created by gsg on 12/06/18.
*/
/*
 * OOBE file fields
 */
#define MAIN_URL            "main_url"
#define ACTIVATION_KEY      "activation_key"

/*
 * proxy configuration file fields(copypast from pc_settings.c
 */
#define PROXY_MAIN_CLOUD_URL_FILE_NAME "MAIN_CLOUD_URL_FILE_NAME"
#define PROXY_AUTH_TOKEN_FILE_NAME      "AUTH_TOKEN_FILE_NAME"
#define PROXY_DEVICE_ID                 "DEVICE_ID"

#define GET_OOBE_CFG_DATA(a) return (strlen(a))?(a):NULL

static char proxy_cfg_filename[OOBE_MAX_URL_LEN] = {0};

static char activation_key[OOBE_ACTIVATION_KEY_LEN] = {0};

static char main_url_filename[OOBE_MAX_URL_LEN] = {0};
static char main_url[OOBE_MAX_URL_LEN] = {0};

static char auth_token[LIB_HTTP_AUTHENTICATION_STRING_SIZE] = {0};
static char auth_token_file_name[OOBE_MAX_URL_LEN] = {0};

static char device_id[OOBE_DEVICE_ID_SIZE] = {0};

static char contact_url[OOBE_MAX_URL_LEN] = {0};

/*
 * Take params from the file generated by Cam
 * Save Main URL in file described in ProxyJSON.conf
 * Save Activation Key & Main URL in memory here) as well
 */
int oobe_getCloudParams(const char* file_name) {
    cJSON* cloud_data = load_file(file_name);
    if(!cloud_data) return 0;

    if(!getStrValue(cloud_data, ACTIVATION_KEY, activation_key, sizeof(activation_key))) return 0;
    if(!getStrValue(cloud_data, MAIN_URL, main_url, sizeof(main_url))) return 0;

    if(!save_one_string_file(oobe_getMainCloudURLFileName(), main_url, MAIN_URL)) return 0;
    return 1;
}
/*
 * Return Activation Key or NULL if no key found
 */
const char* oobe_getActivationKey() {
    GET_OOBE_CFG_DATA(activation_key);
}

/******************************************************************************
 *                              Work with Proxy configuration file
 */

/*
 *  Load AuthToken fila name, deviceID (if any), MainCloudURL file name and MainCloudURL if exists
 */
int oobe_load_config(const char* cfg_file_name) {
    cJSON* proxy_cfg = load_file(cfg_file_name);
    if(!proxy_cfg) return 0;

    strncpy(proxy_cfg_filename, cfg_file_name, sizeof(proxy_cfg_filename)-1);

/* Get Main URL file name and Main Cloud URL itself */
    if(!getStrValue(proxy_cfg, PROXY_MAIN_CLOUD_URL_FILE_NAME, main_url_filename, sizeof(main_url_filename))) { /* Add default! */
        saveStrValue("oobe_load_config", cfg_file_name, PROXY_MAIN_CLOUD_URL_FILE_NAME, DEFAULT_MAIN_URL_FILE_NAME, main_url_filename, sizeof(main_url_filename)-1);
        main_url[0] = '\0';
    }
    read_one_string_file(main_url_filename, main_url, sizeof(main_url)-1, "Main Cloud URL");

/* Get Auth token file name and auth toket itself */
    if(!getStrValue(proxy_cfg, PROXY_AUTH_TOKEN_FILE_NAME, auth_token_file_name, sizeof(auth_token_file_name))) { /* Add default! */
        saveStrValue("oobe_load_config", cfg_file_name, PROXY_AUTH_TOKEN_FILE_NAME, DEFAULT_AUTH_TOKEN_FILE_NAME, auth_token_file_name, sizeof(auth_token_file_name)-1);
        auth_token[0] = '\0';
    }
    read_one_string_file(auth_token_file_name, auth_token, sizeof(main_url)-1, "Auth Token");

/* Get deviceID if any */
    if(!getStrValue(proxy_cfg, PROXY_DEVICE_ID, device_id, sizeof(device_id))) device_id[0] = '\0';

    return 1;
}
const char* oobe_getMainCloudURL() {
    GET_OOBE_CFG_DATA(main_url);
}
const char* oobe_getMainCloudURLFileName() {
    GET_OOBE_CFG_DATA(main_url_filename);
}
const char* oobe_getAuthToken() {       /* return NULL if no value or the value > max_len */
    GET_OOBE_CFG_DATA(auth_token);
}
const char* oobe_getProxyDeviceID() {   /* same... */
    GET_OOBE_CFG_DATA(device_id);
}

int oobe_saveAuthToken(const char* new_at) {           /* Return 1 of success, return 0 if not */
    return save_one_string_file(auth_token_file_name, new_at, "Auth Token");
}

int oobe_saveProxyDeviceID(const char* new_da) {       /* Return 1 of success, return 0 if not */
    return saveStrValue("oobe_saveProxyDeviceID", proxy_cfg_filename, PROXY_DEVICE_ID, new_da, device_id, sizeof(device_id)-1);
}

void oobe_save_contact_url(const char* host, const char* uri, const char* port, int use_ssl) {
    char full_url[LIB_HTTP_MAX_URL_SIZE];

    if(use_ssl)
        strncpy(full_url, OOBE_HTTPS, sizeof(full_url));
    else
        strncpy(full_url, OOBE_HTTP, sizeof(full_url));
    strncat(full_url, ":", sizeof(full_url)-strlen(full_url));
    strncat(full_url, port, sizeof(full_url)-strlen(full_url));
    strncat(full_url, "/", sizeof(full_url)-strlen(full_url));
    strncat(full_url, host, sizeof(full_url)-strlen(full_url));


}
const char* oobe_get_contact_url() {

}
